### ISSUE TITLE
passing data

### ISSUE THREAD

**Issue by AlainMus** [oddcb/ionic-split-pane-example#1]
I'm sorry, it's not really an issue with the example itself but more a question and i didn't know where to ask it :)

I recreated it with the example to guide me, and everything works perfect.

The only problem i'm having is that i want to pass information from the menu to the content side.

Let's say i have a list of products and a detail page showing the information based on what product it gets passed to.

if the menu would be the products list, how would i pass the product to the details page on the content side?

i tried doing it in the SplitCommunication.ts 
`  pushPage(page:any, params:any) {
    this.pushSubject.next(page, params);
  }`
like this, but parameters dont match with the .next()

i hope the question is clear, if not let me know and i will try to explain it better.

**Comment by oddcb** [comment]
Hi! Thanks for the question. 

The SplitCommunication itself is just a simple service for providing Observer/Observable. What you can do is change what the SplitCommunication service takes as input to an object and then pass that object into the Subject. Then on the other side, where you subscribe to the observable of the subject you will get the same object. You can then pass whole or parts of that object through to the nav params when you do a push or setRoot. 

I've updated the repository with an example of this (navigate to the 3rd level) and some other important changes (unsubscription of the split communication Observables).

Hope this helps!

**Comment by oddcb** [comment]
Also as an alternative to using RxJS for the menu/content communication is to use Ionics event system: https://ionicframework.com/docs/v2/api/util/Events

**Comment by AlainMus** [comment]
Sweet thanks, i kinda had it figured out before you responded though. i am passing an object now and can access the data.

However i still get some crashes.
![image](https://cloud.githubusercontent.com/assets/18419088/24206162/be2acaf0-0f1d-11e7-9542-ac78199ffed9.png)

i did uncomment the `this.menuCtrl.enable(true, "menu1");` but i still get the error.

edit: 
i also changed it to use the subscription method but it still crashes.
the crash occurs when the split pane is loaded for the second time and you then click something in the content area

**Comment by oddcb** [comment]
Yes. Same problem I struggled with. I also commited a change to prevent this behaviour. You have to make sure you unsubscribe the subscriptions when ionViewWillUnload lifecycle event is triggered. Its in the example from earlier today.

**Comment by oddcb** [comment]
Did you get it to work @AlainMus ?

**Comment by AlainMus** [comment]
Yes, it's working now.
 I did do the unsubscribe but i added another subject and forgot to unsubscribe to that one.
